#  Database AuthMeReloaded configuration file

# What type of database do you want to use? Avariable options: sqlite, mysql, redis
backend: sqlite
# Do you like to cache all the queries? (Performance Boost)
caching: true

# Database Name
databaseName: authme
# Table of the database
tableName: authme

# MySql Database connection settings
# Avariable only if the AuthMeReloaded-Mysql module is installed!
mysql:
    port: '3306'
    host: 127.0.0.1
    username: authme
    password: '12345'

# Redis Database connection settings
# Avariable only if the AuthMeReloaded-Redis module is installed!
redis:
    # Get Redis from http://redis.io/
    host: 127.0.0.1
    port: 6379
    # If your Redis server uses AUTH, set here the password.
    password: ""

# Database column names
columnNames:
    idColumn: id
    nameColumn: username
    realNameColumn: realname
    passwordColumn: password
    ipColumn: ip
    emailColumn: email
    loginStatusColumn: loginstatus
    lastLoginColumn: lastlogin
    lastlLocationXColumn: x
    lastLocationYColumn: y
    lastLocationZColumn: z
    lastLocationWorldColumn: world

backup:
    # Enable or disable Automatic Backup of the SQLite database, destination path: "/AuthMe/backups/%date%/%timestamp%.sql"
    ActivateBackup: false
    # Interval time (in minutes), set to 0 to disable periodic backup
    Interval: 300
    # Do you want to perform a Backup when the server starts?
    OnServerStart: false
    # Do you want to perform a Backup when the server stops?
    OnServerStop: true

purge:
    # Does AuthMe need to purge automatically old unused accounts?
    useAutoPurge: false
    # Number of Days required to mark an account as Unused
    daysBeforeRemovePlayer: 60
    # What to remove
    remove:
        playerInventoryFile: true
        essentialsFiles: true
        permissions: true
        limitedCreativesInventories: true
        antiXRayFiles: true
    # World where players.dat are stored (necessary to remove inventory files)
    defaultWorld: 'world'
